default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: <%= ENV['DATABASE_PATH'] || 'db/development.sqlite3' %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DATABASE_PATH'] || 'db/test.sqlite3' %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  database: sample_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
