default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: <%= ENV['DATABASE_PATH'] || 'db/development.sqlite3' %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DATABASE_PATH'] || 'db/test.sqlite3' %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: <%= ENV['DATABASE_URL'] || 'zodiac_api_database' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'your_database_username' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'your_database_password' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
